### ISSUE TITLE
No license listed

### ISSUE THREAD

**Issue by unixorn** [andela-abankole/chi#2]
There isn't a license statement in the code. I recommend Apache 2 or GPL, but it would be nice to have the license spelled out either in the code or the readme or both.

**Comment by akinjide** [comment]
Thank you

I will do that

**Comment by unixorn** [comment]
Thanks. BTW, I added your theme to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins)

**Comment by akinjide** [comment]
A LICENSE.md file is now present
